[2024-04-09T18:50:51.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T18:50:51.384+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-10T00:00:00+00:00 [queued]>
[2024-04-09T18:50:51.398+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-10T00:00:00+00:00 [queued]>
[2024-04-09T18:50:51.399+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-04-09T18:50:51.443+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_fruit_data> on 2023-03-10 00:00:00+00:00
[2024-04-09T18:50:51.457+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2530) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T18:50:51.459+0000] {standard_task_runner.py:63} INFO - Started process 2534 to run task
[2024-04-09T18:50:51.459+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'insert_fruit_data', 'scheduled__2023-03-10T00:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmp9ied5byu']
[2024-04-09T18:50:51.464+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask insert_fruit_data
[2024-04-09T18:50:51.538+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.insert_fruit_data scheduled__2023-03-10T00:00:00+00:00 [running]> on host fd38698150f5
[2024-04-09T18:50:51.822+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='insert_fruit_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-10T00:00:00+00:00'
[2024-04-09T18:50:51.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T18:50:51.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T18:50:51.917+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fruit_table_dag.py", line 12, in insert_fruit_data_into_db
    conn = Variable.get('eskplorasi_postgres')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable eskplorasi_postgres does not exist'
[2024-04-09T18:50:51.955+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fruits_dag, task_id=insert_fruit_data, execution_date=20230310T000000, start_date=20240409T185051, end_date=20240409T185051
[2024-04-09T18:50:52.029+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 261 for task insert_fruit_data ('Variable eskplorasi_postgres does not exist'; 2534)
[2024-04-09T18:50:52.108+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T18:50:52.198+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T18:50:52.220+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
