[2024-04-09T14:48:42.731+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T14:48:42.887+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fakestore_dag.write_to_txt manual__2024-04-09T14:48:30.762882+00:00 [queued]>
[2024-04-09T14:48:42.944+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fakestore_dag.write_to_txt manual__2024-04-09T14:48:30.762882+00:00 [queued]>
[2024-04-09T14:48:42.945+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-04-09T14:48:43.049+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_txt> on 2024-04-09 14:48:30.762882+00:00
[2024-04-09T14:48:43.084+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2585) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T14:48:43.103+0000] {standard_task_runner.py:63} INFO - Started process 2589 to run task
[2024-04-09T14:48:43.121+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fakestore_dag', 'write_to_txt', 'manual__2024-04-09T14:48:30.762882+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/get_write_data_from_api.py', '--cfg-path', '/tmp/tmp1012jb00']
[2024-04-09T14:48:43.129+0000] {standard_task_runner.py:91} INFO - Job 150: Subtask write_to_txt
[2024-04-09T14:48:43.405+0000] {task_command.py:426} INFO - Running <TaskInstance: fakestore_dag.write_to_txt manual__2024-04-09T14:48:30.762882+00:00 [running]> on host a05b73ef9a4b
[2024-04-09T14:48:43.791+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fakestore_dag' AIRFLOW_CTX_TASK_ID='write_to_txt' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T14:48:30.762882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T14:48:30.762882+00:00'
[2024-04-09T14:48:43.794+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T14:48:43.870+0000] {get_write_data_from_api.py:63} ERROR - Failed to write to TXT file: [Errno 13] Permission denied: '/Prioritas-2'
[2024-04-09T14:48:43.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T14:48:43.873+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_write_data_from_api.py", line 57, in write_to_txt
    os.makedirs(OUTPUT_DIR, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Prioritas-2'
[2024-04-09T14:48:43.977+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fakestore_dag, task_id=write_to_txt, execution_date=20240409T144830, start_date=20240409T144842, end_date=20240409T144843
[2024-04-09T14:48:44.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 150 for task write_to_txt ([Errno 13] Permission denied: '/Prioritas-2'; 2589)
[2024-04-09T14:48:44.143+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T14:48:44.501+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T14:48:44.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
