[2024-04-09T09:11:19.215+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T09:11:19.276+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T09:05:54.988182+00:00 [queued]>
[2024-04-09T09:11:19.297+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T09:05:54.988182+00:00 [queued]>
[2024-04-09T09:11:19.298+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-09T09:11:19.330+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_about_us_directory> on 2024-04-09 09:05:54.988182+00:00
[2024-04-09T09:11:19.344+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1027) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T09:11:19.351+0000] {standard_task_runner.py:63} INFO - Started process 1030 to run task
[2024-04-09T09:11:19.349+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_1', 'create_about_us_directory', 'manual__2024-04-09T09:05:54.988182+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag-1.py', '--cfg-path', '/tmp/tmprv7vt4e_']
[2024-04-09T09:11:19.354+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask create_about_us_directory
[2024-04-09T09:11:19.457+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T09:05:54.988182+00:00 [running]> on host b6bc23c6abe9
[2024-04-09T09:11:19.713+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_1' AIRFLOW_CTX_TASK_ID='create_about_us_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T09:05:54.988182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T09:05:54.988182+00:00'
[2024-04-09T09:11:19.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T09:11:19.727+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T09:11:19.732+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir about_us']
[2024-04-09T09:11:19.794+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T09:11:19.814+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-09T09:11:19.816+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T09:11:19.922+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_1, task_id=create_about_us_directory, execution_date=20240409T090554, start_date=20240409T091119, end_date=20240409T091119
[2024-04-09T09:11:20.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-09T09:11:20.314+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-09T09:11:20.371+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
