[2024-04-09T10:10:30.433+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T10:10:30.548+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T10:10:15.020936+00:00 [queued]>
[2024-04-09T10:10:30.570+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T10:10:15.020936+00:00 [queued]>
[2024-04-09T10:10:30.573+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-09T10:10:30.627+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): create_about_us_directory> on 2024-04-09 10:10:15.020936+00:00
[2024-04-09T10:10:30.648+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1757) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T10:10:30.651+0000] {standard_task_runner.py:63} INFO - Started process 1760 to run task
[2024-04-09T10:10:30.650+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_1', 'create_about_us_directory', 'manual__2024-04-09T10:10:15.020936+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag-1.py', '--cfg-path', '/tmp/tmp6qdalu82']
[2024-04-09T10:10:30.665+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask create_about_us_directory
[2024-04-09T10:10:30.841+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_1.create_about_us_directory manual__2024-04-09T10:10:15.020936+00:00 [running]> on host b6bc23c6abe9
[2024-04-09T10:10:32.018+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_1' AIRFLOW_CTX_TASK_ID='create_about_us_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T10:10:15.020936+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T10:10:15.020936+00:00'
[2024-04-09T10:10:32.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T10:10:32.090+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-09T10:10:32.099+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -p about_us']
[2024-04-09T10:10:32.190+0000] {subprocess.py:86} INFO - Output:
[2024-04-09T10:10:32.231+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-09T10:10:32.278+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T10:10:32.407+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_1, task_id=create_about_us_directory, execution_date=20240409T101015, start_date=20240409T101030, end_date=20240409T101032
[2024-04-09T10:10:32.498+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-09T10:10:32.702+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-09T10:10:32.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
