[2024-04-09T17:54:51.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-09T17:54:52.055+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-08T00:00:00+00:00 [queued]>
[2024-04-09T17:54:52.192+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-08T00:00:00+00:00 [queued]>
[2024-04-09T17:54:52.202+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2024-04-09T17:54:52.264+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2023-03-08 00:00:00+00:00
[2024-04-09T17:54:52.283+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-09T17:54:52.286+0000] {standard_task_runner.py:63} INFO - Started process 1293 to run task
[2024-04-09T17:54:52.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fruits_dag', 'create_fruits_table', 'scheduled__2023-03-08T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/fruit_table_dag.py', '--cfg-path', '/tmp/tmpn6enph_q']
[2024-04-09T17:54:52.295+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask create_fruits_table
[2024-04-09T17:54:52.657+0000] {task_command.py:426} INFO - Running <TaskInstance: fruits_dag.create_fruits_table scheduled__2023-03-08T00:00:00+00:00 [running]> on host fd38698150f5
[2024-04-09T17:54:53.180+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fruits_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2023-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-08T00:00:00+00:00'
[2024-04-09T17:54:53.183+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-09T17:54:53.185+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            family VARCHAR(50) NOT NULL,
            type VARCHAR(50) NOT NULL,
            color VARCHAR(50) NOT NULL
        );
    
[2024-04-09T17:54:53.246+0000] {base.py:84} INFO - Using connection ID 'postgres_eksplorasi' for task execution.
[2024-04-09T17:54:53.338+0000] {base.py:84} INFO - Using connection ID 'postgres_eksplorasi' for task execution.
[2024-04-09T17:54:53.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-09T17:54:53.370+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.20.0.3), port 5432 failed: fe_sendauth: no password supplied

[2024-04-09T17:54:53.480+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fruits_dag, task_id=create_fruits_table, execution_date=20230308T000000, start_date=20240409T175452, end_date=20240409T175453
[2024-04-09T17:54:53.638+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task create_fruits_table (connection to server at "postgres" (172.20.0.3), port 5432 failed: fe_sendauth: no password supplied
; 1293)
[2024-04-09T17:54:53.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-09T17:54:53.906+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-09T17:54:54.014+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-09T17:54:54.034+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
